### ISSUE TITLE
(Request) Update for 1.19.2

### ISSUE THREAD

**Issue by pinecoffin** [sschr15/no-double-tap-sprint#1]
Hey sschr15,

I was hoping to use this mod as the double tap sprint is driving me crazy and so far I can't find anything but your mod to fix it. Any chance of updaiting this for 1.19.2? (sorry I have no idea how involved this request is).

Cheers

**Comment by sschr15** [comment]
Done! It should now be [uploaded to Modrinth](https://modrinth.com/mod/double-tap/version/1.0.0) for 1.19.2, but also later versions for people who want it.

**Comment by pinecoffin** [comment]
Wow, you absolute legend! I wasn't sure I'd even get a reply! Thank you very much.

Have a great day.

Sent from Nine<http://www.9folders.com/>
________________________________
