### ISSUE TITLE
The mod breaks sprinting...

### ISSUE THREAD

**Issue by NiaSwift** [sschr15/no-double-tap-sprint#2]
If you hold your sprint key and walk, then stop walking but still be holding your sprint key, you'll still be sprinting because of the mod. You'll see the running particles below you even though you're not moving, and if you jump you'll get pushed forward a little bit, which is really annoying. Also, if you have toggle sprint on like I do, it's even more annoying since you wouldn't even be touching anything and it'd still do the particles and the annoying jump thing if you press your jump key.

**Comment by sschr15** [comment]
Fixed in https://modrinth.com/mod/double-tap/version/H8p1TdqM
